apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ping.fullname" . }}-frontendConfig
  labels:
    app: {{ template "ping.name" . }}
    chart: {{ template "ping.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  url.foo: {{ .Values.frontendconfig.backendFooUrl }}
  url.bar: {{ .Values.frontendconfig.backendBarUrl }}
