apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nodeweb
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: nodeweb
  targetCPUUtilizationPercentage: 30