apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nodeweb
spec:
  template:
    metadata:
      labels:
        app: nodeweb
    spec:
      containers:
      - name: nodeweb
        image: melvinlee/nodeweb
        ports:
          - name: http
            containerPort: 80
        env:
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 250m