apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hitcounter-frontend
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: hitcounter-frontend
  targetCPUUtilizationPercentage: 30